# Generated by Django 6.1.1 on 2026-10-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificacionPrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField(default=0.0, help_text='Latitud del prestador')),
                ('longitud', models.FloatField(default=0.0, help_text='Longitud del prestador')),
            ],
        ),
    ]
